---
- name: Installing a nginx web servers
  hosts: all
  become: yes
  tasks:
    - name: update the packages
      apt:
        update_cache: yes
    - name: install nginx
      apt:
        name: nginx
        state: present
    - name: start the services
      service:
        name: nginx
        state: started